import type { Metadata } from "next";
import NavSchedule from "./components/NavSchedule";
import SchProvider from "./schContext/schAppContext";
import { cookies } from "next/headers";

export const metadata: Metadata = {
    title: "Profile",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const token = cookies().get('token')?.value;
    const fetchLessons = async () => {
        try {
            const res = await fetch(`${process.env.BASE_URL}/api/lesson-weak`, {
                method: "GET",
                headers: {
                    'Authorization': `Bearer ${token}`
                }
            })
            if (!res.ok) {
                return new Error(await res.text())
            }
            return await res.json()
        } catch (error) {
            console.error(error);
        }
    }
    let data = null;
    if (token) {
        data = await fetchLessons()
        return (
            <SchProvider data={data}>
                <div >
                    <NavSchedule />
                    {children}
                </div>
            </SchProvider>
        );
    } else {
        return <div>not allow</div>
    }
}
