import type { Metadata } from "next";
import NavSchedule from "./components/NavSchedule";
import SchProvider from "./schContext/schAppContext";

export const metadata: Metadata = {
    title: "Profile",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SchProvider>
            <div >
                <NavSchedule />
                {children}
            </div>
        </SchProvider>
    );
}
