import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Toaster } from "react-hot-toast";
import axios from "axios";
import AppContextProvider from "./context/appContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
axios.defaults.baseURL = 'http://localhost:3000'
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body className={inter.className}>
        <AppContextProvider>
          <Navbar />
          <Toaster position="bottom-right" />
          {children}
        </AppContextProvider>
      </body>
    </html>
  );
}
