import type { Metadata } from "next";
import Sidebar from "./components/Sidebar";
import { getRole } from "@/lib/verfiyAuth";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { Suspense } from "react";


export const metadata: Metadata = {
    title: "لوحة التحكم",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const token = cookies().get('token')?.value;
    const user = getRole(token as string);
    if (!user || (user.role !== 'admin')) {
        redirect('/');
    }
    return (
        <Suspense fallback={"loading.........."}>
            <div className="flex flex-col lg:flex-row">
                <Sidebar />
                <div className="flex-grow bg-[#cacaca25] lg:px-5">
                    {children}
                </div>
            </div>
        </Suspense>
    );
}
