import type { Metadata } from "next";
import Sidebar from "./components/Sidebar";


export const metadata: Metadata = {
    title: "لوحة التحكم",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex flex-col lg:flex-row">
            <Sidebar />
            <div className="flex-grow bg-[#cacaca25] lg:px-5">
                {children}
            </div>
        </div>
    );
}
